#include "core.hpp"

Expr::Expr(GroupType group_type,
           OpType op_type,
           LinkType link_type,
           std::string_view group,
           std::string_view op,
           std::string_view link,
           size_t ref_id,
           size_t idx,
           size_t depth,
           Expr* parent,
           std::vector<std::unique_ptr<Expr>> children,
           std::vector<Equation> eqs,
           std::string x_frag,
           std::vector<std::string> b_eqs,
           std::string xvar,
           std::string bvar,
           size_t n,
           size_t m,
           size_t start,
           size_t size,
           bool active)
    : group_type(group_type),
      op_type(op_type),
      link_type(link_type),
      group(group),
      op(op),
      link(link),
      ref_id(ref_id),
      idx(idx),
      depth(depth),
      parent(std::move(parent)),
      children(std::move(children)),
      eqs(std::move(eqs)),
      x_frag(std::move(x_frag)),
      b_eqs(std::move(b_eqs)),
      xvar(std::move(xvar)),
      bvar(std::move(bvar)),
      n(n),
      m(m),
      start(start),
      size(size),
      active(active) {}

